### ISSUE TITLE
Update example_1.xml

### ISSUE THREAD

**Issue by JDziurlaj** [usnistgov/CastVoteRecords#24]
Update `example_1.xml` to use latest examples found in the CVR Specification

**Comment by moldover** [comment]
@JDziurlaj I also found (I think?) a typo:
		<Candidate ObjectId="_C1CN2">
			<Code>
				<Type>local-level</Type>
				<Value>_C1CN3</Value> should be _C1CN2 to match the pattern of the other Candidate objects.

**Comment by JDziurlaj** [comment]
page 75 of the 1500-103 specification references this file, and specific line numbers, so we will be unable to change this example substantially. I've removed the ranks from one of the CVRs as it may be confusing to have a contest change from RCV to non-RCV between CVRs.

**Comment by moldover** [comment]
Gotcha.  In that case, might be worth leaving those alone (or adding some warning comments) and creating additional correct example files.  The examples were super helpful in parsing out the information in NIST 1500-103.
