### ISSUE TITLE
Recall contest not explicitly defined

### ISSUE THREAD

**Issue by carl3** [usnistgov/CastVoteRecords#9]
Thanks to all who worked on the CVR spec.

I noticed that there is no explicit definition of a way to represent recall contests. It's essentially
the same as a retention contest, but the meaning of Yes/No is reversed. Probably, no new
classes are required, but it would be good to add to the documentation/descriptions that a recall contest is represented with a RetentionContest. The semantics of Yes/No selections are independent of the CVR format, but a traditional retention and recall would be interpreted in opposite ways in results reporting.

**Comment by JDziurlaj** [comment]
Would also affect `ElectionResultsReporting`.

**Comment by JDziurlaj** [comment]
Checking the latest CVR specification, this was never added to the documentation. However, given that Ballot Definition supports activation/recall explicitly, and that we should eventually backport those changes, a separate change should not be necessary.
